[build]
  publish = "public"
#  command = "cd aob03 && hugo --gc --themesDir ../.."
#  command = "cd aob03 && hugo"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.73.0"
#  HUGO_THEME = "repo"
#  HUGO_BASEURL = "/"